version: "3.9"
   
services:

  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: panel_web
    working_dir: /code/src
    restart: on-failure
    
    command: bash -c "python3 -m panel serve Interactive_dashboard.ipynb --autoreload"

    environment:
      DEBUG: 1
    volumes:
      - ./src:/code/src
    ports:
      - "5006:5006"


